services:
    postgres:
        image: postgres:latest
        container_name: postgres_db
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: main
        ports:
            - '5433:5432'
