services:
    postgres_db:
        image: postgres:latest
        container_name: postgres_db
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: main
        ports:
            - '5433:5432'
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        networks:
            - personal_site_network

    app:
        build: .
        container_name: personal_site_app
        restart: unless-stopped
        ports:
            - '3000:3000'
        depends_on:
            - postgres_db
        volumes:
            - ./blog:/app/blog
        networks:
            - personal_site_network

networks:
    personal_site_network:
        driver: bridge
volumes:
    uploads_data: {}
