services:
    postgres_db:
        image: postgres:latest
        container_name: postgres_db
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: main
        ports:
            - '5433:5432'
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        networks:
            - personal_site_network

    app:
        build: .
        container_name: personal_site_app
        restart: unless-stopped
        ports:
            - '3000:3000'
        depends_on:
            - postgres_db
        volumes:
            - uploads_data:/public/uploads
        networks:
            - personal_site_network

    nginx:
        image: nginx:latest
        container_name: nginx_server
        restart: unless-stopped
        ports:
            - '8081:80'
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./blog/published:/usr/share/nginx/uploads/blog/published:ro
        networks:
            - personal_site_network
networks:
    personal_site_network:
        driver: bridge
volumes:
    uploads_data: {}
